cd build
cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_INSTALL_PREFIX=D:\项目\Simulater_FreeRTOS_CycloneDDS\ddslib -DBUILD_EXAMPLES=ON .. -DENABLE_SSL=NO -DENABLE_ICEORYX=NO -DENABLE_TYPELIB=NO -DENABLE_TYPE_DISCOVERY=NO -DENABLE_TOPIC_DISCOVERY=NO -DENABLE_SOURCE_SPECIFIC_MULTICAST=NO -DENABLE_IPV6=NO -DBUILD_IDLC_XTESTS=NO -DENABLE_SECURITY=NO -DBUILD_TESTING=NO -DBUILD_DDSPERF=NO DBUILD_SHARED_LIBS=OFF
cmake --build . --parallel
cmake --build . --target install
